### ISSUE TITLE
Feature: API to set/change values of a page from outside

### ISSUE THREAD

**Issue by crackwitz** [splitbrain/dokuwiki-plugin-data#192]
Hi!

I have a bunch of pages that stand for electrical parts. Each page contains a stock count. I'd like to be able to manipulate this value with a POST request from somewhere outside the wiki (querying would be nice too!).

I imagine this would work like the custom entry editor, but just updating the fields that were given in the request.

Simple math for incrementing and decrementing would be nice, but is maybe too type-specific.

**Comment by Klap-in** [comment]
This plugin, the data plugin, has technical limitations why such an API is not easy to built.

Since some time an alternative plugin is developed: https://www.dokuwiki.org/plugin:struct
This plugin is internally significant different, and therefore the its use and syntax too if compared to the data plugin. But with some effort it can replace the data plugin.

For you an interesting part could be the availability of a remote API:
https://www.dokuwiki.org/plugin:struct:remote_api
